import type { Metadata } from "next";
import { AuthProvider } from "@/contexts/AuthContext";
import { Inter } from "next/font/google";
import Link from "next/link";
import Navbar from "@/components/navbar";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-50 min-h-screen flex flex-col`}
      >
        <AuthProvider>
          <Navbar />
          <main className="">
            {children}
          </main>
          
        </AuthProvider>
      </body>
    </html>
  );
}
